In [1]:
import numpy as np

In [3]:
a = np.arange(1,10)

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = range(1,10)

In [7]:
print(x)

range(1, 10)


In [8]:
print(list(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
# further changes examples:
x = np.arange(10.4)

In [10]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.arange(0.5,10.4,0.8)

array([ 0.5,  1.3,  2.1,  2.9,  3.7,  4.5,  5.3,  6.1,  6.9,  7.7,  8.5,
        9.3, 10.1])

In [12]:
np.arange(0.5,10.4,0.8,int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# linspace
# 50 values between 1 and 10:
print(np.linspace(1,10,50))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [16]:
# 7 values between 1 and 10:
print(np.linspace(1,10,7))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [17]:
# excluding the endpoint:
print(np.linspace(1,10,7,endpoint=False))

[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [18]:
print(np.linspace(1,9,7))

[1.         2.33333333 3.66666667 5.         6.33333333 7.66666667
 9.        ]


In [19]:
print(np.linspace(1,9))

[1.         1.16326531 1.32653061 1.48979592 1.65306122 1.81632653
 1.97959184 2.14285714 2.30612245 2.46938776 2.63265306 2.79591837
 2.95918367 3.12244898 3.28571429 3.44897959 3.6122449  3.7755102
 3.93877551 4.10204082 4.26530612 4.42857143 4.59183673 4.75510204
 4.91836735 5.08163265 5.24489796 5.40816327 5.57142857 5.73469388
 5.89795918 6.06122449 6.2244898  6.3877551  6.55102041 6.71428571
 6.87755102 7.04081633 7.20408163 7.36734694 7.53061224 7.69387755
 7.85714286 8.02040816 8.18367347 8.34693878 8.51020408 8.67346939
 8.83673469 9.        ]


In [21]:
# retstep examples:
samples,spacing = np.linspace(1,10,retstep=True)
print(spacing)

0.1836734693877551


In [23]:
# zero dimensional arrays in numpy:
x = np.array(42)
print("x: ",x)
print('The type of x: ',type(x))
print('The dimension of x: ',np.ndim(x))

x:  42
The type of x:  <class 'numpy.ndarray'>
The dimension of x:  0


In [24]:
# one dimensional arrays:
F = np.array([1,2,3,5,8,13,21])
V = np.array([3.4,6.9,99.8,12.8])

print('F: ',F)
print('V: ',V)

print('Type of F: ',F.dtype)
print('Type of V: ',V.dtype)

print('Dimension of F: ',np.ndim(F))
print('Dimension of V: ',np.ndim(V))

F:  [ 1  2  3  5  8 13 21]
V:  [ 3.4  6.9 99.8 12.8]
Type of F:  int32
Type of V:  float64
Dimension of F:  1
Dimension of V:  1


In [28]:
# two dimensional arrays:
A = np.array([[3.4,8.7,9.9],
            [1.1,-7.8,-0.7],
            [4.1,12.3,4.8]])
print(A)
print(np.ndim(A))

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
2


In [29]:
# shape of the array:
x = np.array([[67,63,87],
             [77,69,59],
             [85,87,99],
             [79,72,71],
             [63,89,93],
             [68,92,78]])

print(np.shape(x))

(6, 3)


In [30]:
x

array([[67, 63, 87],
       [77, 69, 59],
       [85, 87, 99],
       [79, 72, 71],
       [63, 89, 93],
       [68, 92, 78]])

In [31]:
x.shape = (3,6)

In [32]:
x

array([[67, 63, 87, 77, 69, 59],
       [85, 87, 99, 79, 72, 71],
       [63, 89, 93, 68, 92, 78]])

In [34]:
# indexing and slicing
F = np.array([1,1,2,3,5,8,13,21])

# print the first element of F
print(F[0])

# print the last element of F
print(F[-1])

1
21


In [35]:
# indexing multiple dimension arrays:
A = np.array([[3.4,8.7,9.9],
             [1.1,-7.8,-0.7],
             [4.1,12.3,4.8]])
print(A[1][0])

1.1


In [36]:
# another way of accesing elements of multi-dimension array:
print(A[1,0])

1.1


In [37]:
S = np.array([0,1,2,3,4,5,6,7,8,9])
print(S[2:5])
print(S[:4])
print(S[:])

[2 3 4]
[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [39]:
# slicing operator on multi-dimension numpy arrays:
A = np.array([[11,12,13,14,15],
             [21,22,23,24,25],
             [31,32,33,34,35],
             [41,42,43,44,45],
             [51,52,53,54,55]])
print(A)

print(A[:3,2:])

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [40]:
X = np.arange(28).reshape(4,7)
print(X)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [41]:
#print(A[start:stop:step])
print(X[::2,::3])

[[ 0  3  6]
 [14 17 20]]


In [45]:
A = np.arange(100).reshape(5,20)
B = np.arange(200).reshape(10,20)

print(A)
print(B)

# checking if they share memory or not
print(np.may_share_memory(A,B))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [16

In [46]:
# Arrays of zero's and one's:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
print(np.ones_like(A))
print(np.zeros_like(B))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [54]:
# copying arrays
Arr = np.copy(X)
print(Arr)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [55]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [56]:
# EXERCISES:
v = np.arange(10)
print(v)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
# creates odd indices:
print(v[1::2])

[1 3 5 7 9]


In [58]:
# create backward oddering of v:
print(v[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [59]:
# output of the following:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


In [60]:
#creating a two dimensional array:
m = np.arange(200).reshape(20,10)
print(m)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [62]:
# element of each row in reverse order
print(m[:,::-1])

[[  9   8   7   6   5   4   3   2   1   0]
 [ 19  18  17  16  15  14  13  12  11  10]
 [ 29  28  27  26  25  24  23  22  21  20]
 [ 39  38  37  36  35  34  33  32  31  30]
 [ 49  48  47  46  45  44  43  42  41  40]
 [ 59  58  57  56  55  54  53  52  51  50]
 [ 69  68  67  66  65  64  63  62  61  60]
 [ 79  78  77  76  75  74  73  72  71  70]
 [ 89  88  87  86  85  84  83  82  81  80]
 [ 99  98  97  96  95  94  93  92  91  90]
 [109 108 107 106 105 104 103 102 101 100]
 [119 118 117 116 115 114 113 112 111 110]
 [129 128 127 126 125 124 123 122 121 120]
 [139 138 137 136 135 134 133 132 131 130]
 [149 148 147 146 145 144 143 142 141 140]
 [159 158 157 156 155 154 153 152 151 150]
 [169 168 167 166 165 164 163 162 161 160]
 [179 178 177 176 175 174 173 172 171 170]
 [189 188 187 186 185 184 183 182 181 180]
 [199 198 197 196 195 194 193 192 191 190]]


In [63]:
# rows are in reverse order:
print(m[::-1,:])

[[190 191 192 193 194 195 196 197 198 199]
 [180 181 182 183 184 185 186 187 188 189]
 [170 171 172 173 174 175 176 177 178 179]
 [160 161 162 163 164 165 166 167 168 169]
 [150 151 152 153 154 155 156 157 158 159]
 [140 141 142 143 144 145 146 147 148 149]
 [130 131 132 133 134 135 136 137 138 139]
 [120 121 122 123 124 125 126 127 128 129]
 [110 111 112 113 114 115 116 117 118 119]
 [100 101 102 103 104 105 106 107 108 109]
 [ 90  91  92  93  94  95  96  97  98  99]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 10  11  12  13  14  15  16  17  18  19]
 [  0   1   2   3   4   5   6   7   8   9]]


In [64]:
# rows and columns are in reverse order:
print(m[::-1,::-1])

[[199 198 197 196 195 194 193 192 191 190]
 [189 188 187 186 185 184 183 182 181 180]
 [179 178 177 176 175 174 173 172 171 170]
 [169 168 167 166 165 164 163 162 161 160]
 [159 158 157 156 155 154 153 152 151 150]
 [149 148 147 146 145 144 143 142 141 140]
 [139 138 137 136 135 134 133 132 131 130]
 [129 128 127 126 125 124 123 122 121 120]
 [119 118 117 116 115 114 113 112 111 110]
 [109 108 107 106 105 104 103 102 101 100]
 [ 99  98  97  96  95  94  93  92  91  90]
 [ 89  88  87  86  85  84  83  82  81  80]
 [ 79  78  77  76  75  74  73  72  71  70]
 [ 69  68  67  66  65  64  63  62  61  60]
 [ 59  58  57  56  55  54  53  52  51  50]
 [ 49  48  47  46  45  44  43  42  41  40]
 [ 39  38  37  36  35  34  33  32  31  30]
 [ 29  28  27  26  25  24  23  22  21  20]
 [ 19  18  17  16  15  14  13  12  11  10]
 [  9   8   7   6   5   4   3   2   1   0]]


In [66]:
# cut-off the first and the last row and first and the last column:
print(m[1:-1,1:-1])

[[ 11  12  13  14  15  16  17  18]
 [ 21  22  23  24  25  26  27  28]
 [ 31  32  33  34  35  36  37  38]
 [ 41  42  43  44  45  46  47  48]
 [ 51  52  53  54  55  56  57  58]
 [ 61  62  63  64  65  66  67  68]
 [ 71  72  73  74  75  76  77  78]
 [ 81  82  83  84  85  86  87  88]
 [ 91  92  93  94  95  96  97  98]
 [101 102 103 104 105 106 107 108]
 [111 112 113 114 115 116 117 118]
 [121 122 123 124 125 126 127 128]
 [131 132 133 134 135 136 137 138]
 [141 142 143 144 145 146 147 148]
 [151 152 153 154 155 156 157 158]
 [161 162 163 164 165 166 167 168]
 [171 172 173 174 175 176 177 178]
 [181 182 183 184 185 186 187 188]]
